#!/usr/bin/env bash

export PATH="c/Program Files/dotnet/:$PATH"

echo "Formatting code!!"

files=`git diff --cached --name-only --diff-filter ACMR | xargs`
if [ -n "$files" ]; then
    dotnet.exe format -v n --include $files

    git add $files
fi

echo 0
